/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-10-30 05:53:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/BESHOP_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/be/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1571811716555L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link type=\"text/css\" href=\"css/insert.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#btn_Auth\").hide();\r\n");
      out.write("\t\t$(\"#emailcode\").hide();\r\n");
      out.write("\t\t$(\"#btn_email\").click(function(){\r\n");
      out.write("\t\t\t$(\"#btn_email\").hide();\r\n");
      out.write("\t\t\t$(\"#btn_Auth\").show();\r\n");
      out.write("\t\t\t$(\"#emailcode\").show();\r\n");
      out.write("\t\t\tvar email=$(\"#email\").val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({url:\"mail.go\",dataType:\"GET\",data:{\"email\":email},success:function(r){\r\n");
      out.write("\t\t\t\talert(r);\r\n");
      out.write("\t\t\t}});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#btn_Auth\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar emailcode=$(\"#emailcode\").val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"mailok.go\",\r\n");
      out.write("\t\t\t\tdata:{\"emailcode\":emailcode},\r\n");
      out.write("\t\t\t\tsuccess:function(r){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t$(\"#emailcode\").hide();\r\n");
      out.write("\t\t$(\"#btn_email\").click(function(){\r\n");
      out.write("\t\t\t$(\"#emailcode\").show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor (i = new Date().getFullYear(); i > 1900; i--){\r\n");
      out.write("\t        $('#year').append($('<option />').val(i).html(i));\r\n");
      out.write("\t    }\r\n");
      out.write("\t    //populate our months select box\r\n");
      out.write("\t    for (i = 1; i < 13; i++){\r\n");
      out.write("\t        $('#mon').append($('<option />').val(i).html(i));\r\n");
      out.write("\t    }\r\n");
      out.write("\t    //populate our Days select box\r\n");
      out.write("\t    updateNumberOfDays(); \r\n");
      out.write("\r\n");
      out.write("\t    //\"listen\" for change events\r\n");
      out.write("\t    $('#year, #mon').change(function(){\r\n");
      out.write("\t        updateNumberOfDays(); \r\n");
      out.write("\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t \t//var sex = $('input:radio[name=\"gender\"]:checked').val();\r\n");
      out.write("\t$(\"#btn_insert\").click(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("\tfunction updateNumberOfDays(){\r\n");
      out.write("    $('#day').html('');\r\n");
      out.write("    month = $('#mon').val();\r\n");
      out.write("    year = $('#year').val();\r\n");
      out.write("    days = daysInMonth(month, year);\r\n");
      out.write("\r\n");
      out.write("    for(i=1; i < days+1 ; i++){\r\n");
      out.write("            $('#day').append($('<option />').val(i).html(i));\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t//helper function\r\n");
      out.write("\tfunction daysInMonth(month, year) {\r\n");
      out.write("\t    return new Date(year, month, 0).getDate();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction sendIt(){\r\n");
      out.write("\t\tvar email = document.f.email.value;\r\n");
      out.write("        var regex = /^([\\w-]+(?:\\.[\\w-]+)*)@((?:[\\w-]+\\.)*\\w[\\w-]{0,66})\\.([a-z]{2,6}(?:\\.[a-z]{2})?)$/;\r\n");
      out.write("        \r\n");
      out.write("        if (f.beuid.value == \"\") {\r\n");
      out.write("        \t$('#id_check').text('아이디를 입력해주세요');\r\n");
      out.write("           \r\n");
      out.write("            f.beuid.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        for (i = 0; i < document.f.beuid.value.length; i++) {\r\n");
      out.write("            ch = document.f.beuid.value.charAt(i)\r\n");
      out.write("            if (!(ch >= '0' && ch <= '9') && !(ch >= 'a' && ch <= 'z')&&!(ch >= 'A' && ch <= 'Z')) {\r\n");
      out.write("            \t$('#id_check').text(\"아이디는 대소문자, 숫자만 입력가능합니다.\");\r\n");
      out.write("                \r\n");
      out.write("                document.f.beuid.focus()\r\n");
      out.write("                document.f.beuid.select()\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        if (document.f.beuid.value.indexOf(\" \") >= 0) {\r\n");
      out.write("            \r\n");
      out.write("            $('#id_check').text(\"아이디에 공백을 사용할 수 없습니다.\");\r\n");
      out.write("            document.f.beuid.focus()\r\n");
      out.write("            document.f.beuid.select()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (document.f.beuid.value.length<4 || document.f.beuid.value.length>12) {\r\n");
      out.write("            \r\n");
      out.write("            $('#id_check').text(\"아이디를 4~12자까지 입력해주세요.\");\r\n");
      out.write("            document.f.beuid.focus()\r\n");
      out.write("            document.f.beuid.select()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (document.f.upw.value == \"\") {\r\n");
      out.write("        \t$('#pw_check').text(\"비밀번호를 입력하지 않았습니다.\");\r\n");
      out.write("            \r\n");
      out.write("            document.f.upw.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        //\r\n");
      out.write("        if (f.upw.value == f.beuid.value) {\r\n");
      out.write("        \t$('#pw_check').text(\"아이디와 비밀번호가 같습니다.\");\r\n");
      out.write("            \r\n");
      out.write("            document.f.upw.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        //비밀번호 길이 체크(4~8자 까지 허용)\r\n");
      out.write("        if (document.f.upw.value.length<4 || document.f.upw.value.length>12) {\r\n");
      out.write("        \t$('#pw_check').text(\"비밀번호를 4~12자까지 입력해주세요.\")\r\n");
      out.write("            document.f.upw.focus()\r\n");
      out.write("            document.f.upw.select()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        //비밀번호와 비밀번호 확인 일치여부 체크\r\n");
      out.write("        if (document.f.upw.value != document.f.upw_check.value) {\r\n");
      out.write("        \t$('#pwd_check').text(\"비밀번호가 일치하지 않습니다\");\r\n");
      out.write("            \r\n");
      out.write("            document.f.upw_check.value = \"\"\r\n");
      out.write("            document.f.upw_check.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write(" \r\n");
      out.write("        if (document.f.email.value == \"\") {\r\n");
      out.write("        \t$('#email_check').text(\"이메일을 입력하지 않았습니다.\");\r\n");
      out.write("            \r\n");
      out.write("            document.f.email.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (regex.test(email) === false) {\r\n");
      out.write("        \t\r\n");
      out.write("        \t$('#email_check').text(\"잘못된 이메일 형식입니다.\");\r\n");
      out.write("            document.f.email.value=\"\"\r\n");
      out.write("            document.f.email.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if (document.f.uname.value == \"\") {\r\n");
      out.write("        \t$('#name_check').text(\"이름을 입력하지 않았습니다.\")\r\n");
      out.write("            document.f.uname.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(document.f.uname.value.length<2){\r\n");
      out.write("        \t$('#name_check').text(\"이름을 2자 이상 입력해주십시오.\")\r\n");
      out.write("            document.f.uname.focus()\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(document.f.pf1.selected==false && \r\n");
      out.write("                document.f.pf2.selected==false && \r\n");
      out.write("                document.f.pf3.selected==false){\r\n");
      out.write("        \t$('#pf_check').text(\"관심분야를 선택 주세요\");\r\n");
      out.write("             return false;\r\n");
      out.write("          }\r\n");
      out.write("        if(document.f.sex.checked==false && \r\n");
      out.write("                document.f.sex.checked==false){\r\n");
      out.write("        \t$('#sex_check').text(\"성별을 체크해 주세요\");\r\n");
      out.write("             return false;\r\n");
      out.write("          }\r\n");
      out.write("        if(document.f.emailcode==\"\"){\r\n");
      out.write("        \t$('#code_check').text(\"\");\r\n");
      out.write("             return false;\r\n");
      out.write("          }\r\n");
      out.write("        \r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 id=\"logo\">BESHOP</h1>\r\n");
      out.write("    <div id=\"f_insert\">\r\n");
      out.write("        <form method=\"post\" action=\"/be/joinpage\"  name=\"f\" onsubmit=\"return sendIt();\">\r\n");
      out.write("             <p>아이디</p><span><input type=\"text\" name=\"beuid\" id=\"beuid\"  maxlength=\"12\" ></span><br>\r\n");
      out.write("            <div class=\"check_font\" id=\"id_check\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("           <p>비밀번호</p><span><input type=\"password\" name=\"upw\" id=\"upw\" maxlength=\"12\" ></span><br>\r\n");
      out.write("            <div class=\"check_font\" id=\"pw_check\"></div>\r\n");
      out.write("            <p>비밀번호 재확인</p><span><input type=\"password\" name=\"upw_check\" id=\"upw_check\"  maxlength=\"12\" ></span><br>\r\n");
      out.write("            <div class=\"check_font\" id=\"pwd_check\"></div>\r\n");
      out.write("             <p>이름</p><span><input type=\"text\" name=\"uname\" id=\"uname\"  maxlength=\"5\" ></span><br>\r\n");
      out.write("             <div class=\"check_font\" id=\"name_check\"></div>\r\n");
      out.write("            <p>생년월일</p>\r\n");
      out.write("            \r\n");
      out.write("            <select id=\"year\" name=\"year\"></select>년\r\n");
      out.write("            <select id=\"mon\" name=\"mon\"></select>월\r\n");
      out.write("            <select id=\"day\" name=\"day\"></select>일\r\n");
      out.write("\r\n");
      out.write("             \r\n");
      out.write("            <p>성별</p>\r\n");
      out.write("            <span><input type=\"checkbox\" value=\"여자\" id=\"sex\" name=\"sex\">여자</span>\r\n");
      out.write("            <span><input type=\"checkbox\" value=\"남자\" id=\"sex\" name=\"sex\">남자</span>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"check_font\" id=\"sex_check\"></div>\r\n");
      out.write("            <p>이메일</p>\r\n");
      out.write("             <span><input type=\"text\" name=\"email\" id=\"email\" placeholder=\"이메일을 입력해주세요.\"></span> \r\n");
      out.write("             <span><input type=\"text\" name=\"emailcode\" id=\"emailcode\" placeholder=\"인증번호를 입력해주세요.\"></span> \r\n");
      out.write("             <div class=\"check_font\" id=\"email_check\"></div> \r\n");
      out.write("             <input type=\"button\" id=\"btn_email\" value=\"인증번호받기\">\r\n");
      out.write("             <input type=\"button\" id=\"btn_Auth\" value=\"인증확인\">\r\n");
      out.write("             <div class=\"check_font\" id=\"code_check\"></div> \r\n");
      out.write("              \r\n");
      out.write("             \r\n");
      out.write("            <br>\r\n");
      out.write("            <p>휴대전화</p>\r\n");
      out.write("            <input type=\"number\" name=\"phone1\" id=\"phone1\" value=\"010\">\r\n");
      out.write("            <input type=\"number\" name=\"phone2\" id=\"phone2\" maxlength=\"4\">\r\n");
      out.write("            <input type=\"number\" name=\"phone3\" id=\"phone3\" maxlength=\"4\"><br>\r\n");
      out.write("           <div class=\"check_font\" id=\"phone_check\"></div>\r\n");
      out.write("            <p>선호 카테고리1</p>\r\n");
      out.write("            <select id=\"pf1\" name=\"pf1\">\r\n");
      out.write("            \t<option>선택하세요</option>\r\n");
      out.write("            \t<option value=\"fashion\">패션</option>\r\n");
      out.write("            \t<option value=\"stuff/beauty\">잡화/뷰티</option>\r\n");
      out.write("            \t<option value=\"child\">유아</option>\r\n");
      out.write("            \t<option value=\"food/necessity\">식품/생필품</option>\r\n");
      out.write("            \t<option value=\"hobby/phrases\">문구/취미</option>\r\n");
      out.write("            \t<option value=\"computer\">컴퓨터</option>\r\n");
      out.write("            \t<option value=\"sports\">스포츠</option>\r\n");
      out.write("            \t<option value=\"car/tool\">자동차/공구</option>\r\n");
      out.write("            \t<option value=\"trip/book/ticket\">여행/도서/티켓</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <p>선호 카테고리2</p>\r\n");
      out.write("             <select id=\"pf2\" name=\"pf2\">\r\n");
      out.write("             \t<option>선택하세요</option>\r\n");
      out.write("            \t<option value=\"fashion\">패션</option>\r\n");
      out.write("            \t<option value=\"stuff/beauty\">잡화/뷰티</option>\r\n");
      out.write("            \t<option value=\"child\">유아</option>\r\n");
      out.write("            \t<option value=\"food/necessity\">식품/생필품</option>\r\n");
      out.write("            \t<option value=\"hobby/phrases\">문구/취미</option>\r\n");
      out.write("            \t<option value=\"computer\">컴퓨터</option>\r\n");
      out.write("            \t<option value=\"sports\">스포츠</option>\r\n");
      out.write("            \t<option value=\"car/tool\">자동차/공구</option>\r\n");
      out.write("            \t<option value=\"trip/book/ticket\">여행/도서/티켓</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <p>선호 카테고리3</p>\r\n");
      out.write("             <select id=\"pf3\" name=\"pf3\">\r\n");
      out.write("             \t<option>선택하세요</option>\r\n");
      out.write("            \t<option value=\"fashion\">패션</option>\r\n");
      out.write("            \t<option value=\"stuff/beauty\">잡화/뷰티</option>\r\n");
      out.write("            \t<option value=\"child\">유아</option>\r\n");
      out.write("            \t<option value=\"food/necessity\">식품/생필품</option>\r\n");
      out.write("            \t<option value=\"hobby/phrases\">문구/취미</option>\r\n");
      out.write("            \t<option value=\"computer\">컴퓨터</option>\r\n");
      out.write("            \t<option value=\"sports\">스포츠</option>\r\n");
      out.write("            \t<option value=\"car/tool\">자동차/공구</option>\r\n");
      out.write("            \t<option value=\"trip/book/ticket\">여행/도서/티켓</option>\r\n");
      out.write("            </select>\r\n");
      out.write("             <div class=\"check_font\" id=\"pf_check\"></div>\r\n");
      out.write("            <input type=\"submit\" value=\"가입하기\" onclick=\"sendit()\" id=\"btn_insert\">\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
